language: node_js

node_js:
  - 12

install:
  - npm install

script:
  - npm run test
  - npm run test:e2e

deploy:
  provider: heroku
  app: pokespeare
  api_key:
    secure: lnu8nyL45du9svMh6GndPmnfam8wVzIUIoviMTyvzdIgBoV/puh9QQFncwHWqJGpV13Y3Ldu86o1bTm8k/qywQNhVYOsPqqeJUIen1adWtVslzDB42blJigds2ZAZpSxylt4kYIasvUzMAZS0abnMkPSALrhh0Qr50OpCArofmX1OHQZBtbmxE4lXr2od3LLdthozkPDPY0mruhSLnNCqX7qLxKul8NinmBzZ7H4USBvVStWXO2TT5GJ3G7c4aL5hYv7oj+eXWKibWgcmmaKDHojOQ8xrs+iylE/8giWjqYPJseIovqLGk8PEzBximMHaRAL/yGv2E+hq0danK6Tm+sep/YJkjI/+MyS8Tt9uYT/R26kJ9nblNHM3nTePh5+/YnxN/DSL0V/6XuacO/jT4XBj47w5glQZ745MtoxDgv6FVWNX63QsCPsN7GIZBTkETJhWaC6ysHiYWuOUI1Y1qkclS+yPCBcbrhRIdT69GVUNJfEv+b0Fn7zo06RkAqQ4OQ4h61VgnJsOco3oAEMaWW/VLxQ/dKBtSZ9G2xm/UMSLuVkSY91A8XObY6+GUPXVUMyXaH4RtVfSgCNeEyfssWycUrNFJGwYPKWAiP9D6QMhe9NCznWEZLgEZmOWYlUTL2yZDWpEsQcYZrJO+I0SAfa9eeFr+PhaHI5c13yw4M=
